### ISSUE TITLE
Wow badaix 

### ISSUE THREAD

**Issue by StuartIanNaylor** [badaix/snapweb#1]
Serously many thanks badaix the sheer volume of your quality contributions is just bewildering :)

Many thanks is all I can say.

**Comment by badaix** [comment]
Thanks, glad that you like it. This is still work in progress and my personal playground to learn some web development. 
The project is actually a JavaScript to Typescript refactoring of [snapcast-websockets-ui](https://github.com/derglaus/snapcast-websockets-ui).

**Comment by StuartIanNaylor** [comment]
I saw you make a shout for a webui that was better than the old repo.
There are positives to Covid lockin after all :)

The simplicity and layout of snapcast is about as perefect as you can get it.
Must of been a shed load of work and many thanks are due.
I watch the commits come in via the notifications wow thank you
