### ISSUE TITLE
Error when resuming Snapweb PWA on iPhone

### ISSUE THREAD

**Issue by FredVDB** [badaix/snapweb#10]
I have added the link to the Snapweb page to my iPhone start screen. This way, it gets its own icon, so I don't have to open a browser and navigate to the Snapweb page manually.

However, when unlocking my iPhone and reopening the Snapweb app, I get this message and I have to close the app and reopen it. Is there a way to detect this and reconnect to the Snapserver ?
 
![error snapweb iphone](https://user-images.githubusercontent.com/9460804/94803948-54827b00-03ea-11eb-8618-3e459d1a62ed.png)

**Comment by FredVDB** [comment]
As a temporary workaround I have added an event listener for the visibilitychange event

`document.addEventListener('visibilitychange', handleVisibilityChange, false);`

When the page is shown again, I reinitialize the snapcontrol variable.

**Comment by badaix** [comment]
I'm wondering if audio playback is working on your iPhone?

**Comment by FredVDB** [comment]
Hi, 

the snapwebclient is created successfully on iPhone (IOS 14.0.1), but no audio nor error message

Regards,
Frederik

**Comment by badaix** [comment]
This should be fixed with #23. Can you please check?

**Comment by FredVDB** [comment]
Hello, tested it and works as expected now.

Thx
