### ISSUE TITLE
serialized wrong latency value ?

### ISSUE THREAD

**Issue by kingosticks** [badaix/snapweb#16]
Forgive this unsolicited drive-by code review but shouldn't this be `latency.usec` here? https://github.com/badaix/snapweb/blob/59753301deceb0d221aaa3853612ac974b3b2228/page/snapstream.ts#L156

**Comment by badaix** [comment]
yes, thanks, your completely right!

**Comment by badaix** [comment]
Fixed: fdfac0d32a24e9f666186c6179a29c6fc2ec415c 
This should dramatically improve the time sync :+1:
