### ISSUE TITLE
Data type mismatch between serialize and deserialize methods

### ISSUE THREAD

**Issue by kingosticks** [badaix/snapweb#17]
Maybe realistically this won't be an actual problem but should the data type be consistent between the `serialize` and `deserialize` methods here? One is int32, the other is uint32: https://github.com/badaix/snapweb/blob/59753301deceb0d221aaa3853612ac974b3b2228/page/snapstream.ts#L188

**Comment by badaix** [comment]
Thanks, fixed 39dfce8d66a1e7f5cfef6d40e902413afc9ea567, the value wasn't used anyway, so this was less severe :)

**Comment by kingosticks** [comment]
Thanks for both quick fixes.
