### ISSUE TITLE
Feature to remove clients

### ISSUE THREAD

**Issue by uSpike** [badaix/snapweb#2]
Hello!

I'm using snapweb in a home-assistant add-on here: https://github.com/uSpike/hassio-addons/tree/master/snapserver

I find that I have some clients that I'd like to delete since they have been removed from my system.  I'd much rather have a way to remove them from the web interface, instead of what I have to do now and edit the server's .json file directly.

Cheers!

**Comment by badaix** [comment]
I'm using snapweb with `hide_offline = true` in line 260 of `script.js`. It's planned to have a configuration option for this in the GUI, but for the moment it could help.
