### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by jtrees** [badaix/snapweb#28]
When I try to compile snapweb, I get this:

```
$ make
tsc --build page/tsconfig.json
page/snapcontrol.ts:393:50 - error TS1109: Expression expected.

393     console.log("Snapweb version " + versionElem?.content);
                                                     ~

page/snapcontrol.ts:393:58 - error TS1005: ':' expected.

393     console.log("Snapweb version " + versionElem?.content);
                                                             ~

Makefile:6: recipe for target 'tsc' failed
make: *** [tsc] Error 1
```

I presume I need a specific version of `tsc` (mine is `3.0.3`). Could you add the requirements to the README?

**Comment by jtrees** [comment]
Looks like the `?.` operator was added in Typescript 3.7. I upgraded to 4.1.3 and was able to successfully compile.

**Comment by badaix** [comment]
I've "unmodernized" this line and removed the ?. operator, this optional chaining caused Snapweb not to work on Chrome < 80 and Firefox < 74.
Now it should compile with older TS versions. No idea how to find out which version is at least required.
