### ISSUE TITLE
I want to make a pull request Add in 3-dot menu with show offline clients. slider volume percent.

### ISSUE THREAD

**Issue by poulsp** [badaix/snapweb#33]
I want to make a pull request Add in 3-dot menu with show offline clients. slider volume percent.
But I can't find out to do it, especially now where the develop branch can't compile because of 'MediaMetadata' etc.
What do we do about that?

I have made changes in snapcontrol.ts and styles.css. 

![3Dot](https://user-images.githubusercontent.com/4759224/126910399-4a9c88fc-71b4-451a-a8a7-f546560ca15a.png)

![ShowOfflineClients](https://user-images.githubusercontent.com/4759224/126910439-d2633819-0069-467b-84b2-705cfa30c3ee.png)

![snapcastVolPct](https://user-images.githubusercontent.com/4759224/126910411-a1ca2320-15f4-46dd-b407-7d4585c5efb9.png)

![snapcastAlert](https://user-images.githubusercontent.com/4759224/126910469-6a47bdc2-e590-467a-8dfc-d4b5a3d87104.png)

**Comment by badaix** [comment]
Fixed in [v0.6.0](https://github.com/badaix/snapweb/releases/tag/v0.6.0)
