### ISSUE TITLE
Build fails with latest typescript release

### ISSUE THREAD

**Issue by yubiuser** [badaix/snapweb#44]
3 das ago, `typescript` `5.0.2` was set as `latest`. The build of `snapweb` failes with this release

```
#0 0.088 tsc --build page/tsconfig.json
#35 3.387 page/snapstream.ts(988,61): error TS2345: Argument of type 'number' is not assignable to parameter of type '0 | 1'.
#35 3.415 make: *** [Makefile:6: tsc] Error 1
```

Changing https://github.com/badaix/snapweb/blob/f19a12a3c27d0a4fcbb1058f365f36973c09d033/.github/workflows/ubuntu.yml#L14

to `npm install -g typescript@4.9.5` allows for successful build. 

I don't know if the issue is with `typescript` or a so far undiscovered bug in `snapweb`

**Comment by badaix** [comment]
Fix in develop branch: a621b65c73278f4482aabd2bb42128756139d8f8
