### ISSUE TITLE
this.streamsocket.readyState > Argument of type 'number' is not assignable to parameter of type '0 | 1'

### ISSUE THREAD

**Issue by fledge4tw** [badaix/snapweb#51]
Trying to build on debian bullseye, installed nvm so i installed v18.17.0 to resolve a typescript dependency.

> user@hostname:~$ node -v
v18.17.0

> user@hostname:~$ tsc -v
Version 5.1.6

when i try to build, i get the following error : 

> user@hostname:~$ make
tsc --build page/tsconfig.json
page/snapstream.ts:988:61 - error TS2345: Argument of type 'number' is not assignable to parameter of type '0 | 1'.
988         if ([WebSocket.OPEN, WebSocket.CONNECTING].includes(this.streamsocket.readyState)) {
Found 1 error.
make: *** [Makefile:6: tsc] Error 1

there is an underline on `this.streamsocket.readyState`

Any idea what could go wrong ? Did the language evolve and i'm using an improper version to compile your code ?

Hope this make sense

**Comment by arpena** [comment]
I solved this issue by changing the line 

-        if ([WebSocket.OPEN, WebSocket.CONNECTING].includes(this.streamsocket.readyState)) {

to

+        if (this.streamsocket.readyState == WebSocket.OPEN || this.streamsocket.readyState == WebSocket.CONNECTING) {

Not as succinct, but it works

**Comment by arpena** [comment]
I should add that the current active development branch, [react](https://github.com/badaix/snapweb/tree/react), doesn't have this issue with ts5.

**Comment by badaix** [comment]
Sorry for my newbie question: what is the difference between the develop branch and the react branch with regards to this issue? Is the develop branch using ts4? Will the react framework automatically ship ts5?
There is a pending pull request that introduces the same changes. I should merge it into the react branch, since it should make it more compatible, right?

**Comment by arpena** [comment]
If you are the newbie what is left for us mortals!
I know nothing of ts, but by my tests the react branch compiles fine using ts5. So I guess there is no need to merge the pull request. But then again I wasn't able to get a dist folder out of the react branch...

**Comment by badaix** [comment]
Just noticed that the react branch introduced this fix 7 month ago: 601f0333e2d8e5098fc77b0f36bfe515859d68f7
