### ISSUE TITLE
how to use the GUI? - where can I find a description?

### ISSUE THREAD

**Issue by andrewufrank** [badaix/snapweb#55]
I have a multi-room audio based on snapserver/snapclient working and I have snapweb and snapdroid (as snapcast) on web browser and android. All works nicely and I appreciate the work.
Is there somewhere a description how the GUI works? 
I have on top a square <-> triangle, which can switch. What is the idea? 
It says for each device "default" and I see not what to do with this. 

I assume there is an idea behind it - is there somewhere a description? 

thank you!

**Comment by badaix** [comment]
The square is a stop button, the triangle is a play button. Pretty standard, no documentation required.
