### ISSUE TITLE
Unable to install snapweb package under Raspbian Bullseye

### ISSUE THREAD

**Issue by DesertRider** [badaix/snapweb#73]
I've tried to install snapweb_0.6.0-1_all.deb package on a Raspberry Pi 3 running Debian 11 Bullseye and had this error:

`
dpkg-deb: error: archive '/opt/snapweb_0.6.0-1_all.deb' uses unknown compression for member 'control.tar.zst'
`

What I found consulting my friend Google was that the compression used in the package isn't supported in Debian 11 (okay with Debian 12)...

As I couldn't find a solution concerning the compression problem and dpkg, my solution was to manually download snapweb.zip and decompress it in /usr/share/snapweb/. Pointing this directory in /etc/snapserver.conf made it works.

**Comment by badaix** [comment]
Packages were built with Ubuntu, which is using `zst` compression by default. In Debian support for `zst` was added to `dpkg` 1.21.18 in Debian 12. 
Now I'm forcing `gzip` compression b50f7bce1d5e9d6024d8576c22018f0221fc1623, as applied in this build: https://github.com/badaix/snapweb/actions/runs/8338909351
