### ISSUE TITLE
Docker - snapserver 0.21.0 missing doc_root directory

### ISSUE THREAD

**Issue by bjornstevens** [badaix/snapweb#9]
Hi, since my update to 0.21.0 via docker (ivdata/snapserver) I have not been able to use the webui anymore. It seems like there is no directory anymore where doc_root is configured in the snapserver.conf 

Is there any way to fix this? Do i maybe need to reïnstall the complete docker?

Here is my snapserver.conf:
![afbeelding](https://user-images.githubusercontent.com/23235234/94789348-19298180-03d5-11eb-92f1-17443c57cc07.png)

And here what i see when i try to acces snapweb:
![afbeelding](https://user-images.githubusercontent.com/23235234/94789408-2b0b2480-03d5-11eb-862a-ffe1bb5c9945.png)

**Comment by badaix** [comment]
I'm not aware of any docker container. The default location should be `doc_root = /usr/share/snapserver/snapweb`
I don't think that this is any Snapweb or Snapcast related issue.

**Comment by bjornstevens** [comment]
Changing the location completely fixed it for me, thanks!
