### ISSUE TITLE
ID changes every time 

### ISSUE THREAD

**Issue by fuchsmich** [badaix/snapweb#91]
I'm not sure, if this is the right place to post this issue:

I'm using snapweb client for integrating snapcast on plasma (kde). There is an applet called "web browser", it opens a browser widget.

On the snapserver this client gets a new id every time you start a new desktop session (when the widget gets created).

So the settings (name and latency) get lost.

Could somebody please give me hints on how to investigate and resolve this?

**Comment by badaix** [comment]
Snapweb is using the [localstorage API](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) to persist data. Everytime it starts, it will read the value for the key `uniqueId` from the local storage or create and store one, if it does not exist. 
So it seems that the applet doesn't persist the data.

**Comment by fuchsmich** [comment]
Thank you. Will try to resolve this and report back.

**Comment by fuchsmich** [comment]
In Plasma 6.3 you can use snapweb as applet. I [added](https://invent.kde.org/plasma/kdeplasma-addons/-/commit/7e7a733bc30649542c089f72b0a8ed6606413ec8) persistent storage to webbrowser applet.

![image](https://github.com/user-attachments/assets/4ef5b2bc-06bc-4f53-9da0-595edd468a87)
